<<<<<<< HEAD
name: trader_tycoon_game
description: "Trader Tycoon Game"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  http: ^1.6.0
  cloud_firestore: ^5.6.12
  intl: ^0.20.3
  share_plus: ^10.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
=======
name: trader_tycoon_game
description: "Trader Tycoon Game"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  http: ^1.6.0
  cloud_firestore: ^5.6.12
  intl: ^0.20.3
  share_plus: ^10.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
>>>>>>> af731e055c69737ffe8d73c98c056d703bc928a7
